### ISSUE TITLE
Apply for GNOME Circle

### ISSUE THREAD

**Issue by ghost** [diamondburned/gotk4#121]
Since quite recently, Gtk bindings can apply for the [GNOME Circle](https://circle.gnome.org). This increases the expsosure and visibility of the bindings, which attracts contributors. It's also the closest thing to making the bindings "official", which would also make them a more popular option for app devs.

Apps like [Multiplex](https://github.com/pojntfx/multiplex) prove that the gotk4 bindings are capable of building good, high-quality GNOME apps. Therefore, I recommend applying for inclusion in the GNOME Circle.

**Comment by diamondburned** [comment]
Issue created in https://gitlab.gnome.org/Teams/Circle/-/issues/211.
