### ISSUE TITLE
VTE bindings

### ISSUE THREAD

**Issue by jgillich** [diamondburned/gotk4#127]
I'd like to have a terminal in my app, and [VTE](https://gitlab.gnome.org/GNOME/vte) seems like a good library for that. I've tried to use the generator to create bindings:

```go
package main

//go:generate go run . -o ./pkg/

import (
	"github.com/diamondburned/gotk4/gir/cmd/gir-generate/gendata"
	"github.com/diamondburned/gotk4/gir/cmd/gir-generate/genmain"
	"github.com/diamondburned/gotk4/gir/girgen"
)

const vteModule = "github.com/jgillich/gotk4-vte/pkg"

var postprocessors = map[string][]girgen.Postprocessor{}

var Data = genmain.Overlay(
	gendata.Main,
	genmain.Data{
		Module: vteModule,
		Packages: []genmain.Package{
			{Name: "vte-2.91-gtk4"},
		},
		PkgGenerated: []string{"vte"},
		PkgExceptions: []string{
			"go.mod",
			"go.sum",
			"LICENSE",
		},
	},
)

func main() {
	genmain.Run(Data)
}

```
(not sure if this pkg-config name is standard, there are multiple vte versions on fedora)

Issue is that this generates a crapton of packages

```
$ ls pkg/
adw        cairo           cogl       fontconfig  gdkpixdata  girepository  gobject   gtksource  icalglib  mtk         pangoft2  shew    win32   xrandr
appstream  cally           coglpango  freetype2   gdkwayland  gl            graphene  gvc        libxml2   pango       pangoot   st      xfixes
atk        cloudproviders  dbus       gdk         gdkx11      glib          gsk       harfbuzz   meta      pangocairo  pangoxft  vte     xft
atspi      clutter         dbusglib   gdkpixbuf   gio         gmodule       gtk       ical       metatest  pangofc     shell     vulkan  xlib
```
The generator eventually errors, but I think it shouldn't be generating this much in the first place. Any idea where this could be coming from? Not sure if this is an issue with the generator or the vte gir config...

**Comment by jgillich** [comment]
Aha, played a bit with the generator and it turns out I just needed to add the namespace:

```
{Name: "vte-2.91-gtk4", Namespaces: []string{"Vte-3"}},
```

No idea what the difference between Vte-2 and Vte-3 is though

**Comment by jgillich** [comment]
I *almost* got it working ([repo](https://github.com/jgillich/gotk4-vte/)), but the most important function `vte_pty_spawn_async` is missing, making it rather useless :smile: 

Debug output gives a hint, it's because `Glib.Pid` is skipped



```
girgen: debug: package vte/v3: filtering type GLib.Pid (C.GPid) using filter types.absoluteFilter, trace: github.com/diamondburned/gotk4/gir/cmd/gir-generate/gendata.init @ gendata.go:348
girgen: debug: package vte/v3: ignored type GLib.Pid
girgen: debug: package vte/v3: callback TerminalSpawnAsyncCallback (C.): C arg2 -> Go _pid (in): can't resolve C.GPid
girgen: debug: package vte/v3: callback TerminalSpawnAsyncCallback (C.): C arg2 -> Go _pid (in): cannot resolve type
girgen: debug: package vte/v3: callback TerminalSpawnAsyncCallback (C.): C arg2 -> Go _pid (in): no conversion
girgen: debug: package vte/v3: callback TerminalSpawnAsyncCallback (C.): has no conversion
```

https://github.com/diamondburned/gotk4/blob/132b31b11a5fdc846d09442a7ee8d09084c1cafd/gir/cmd/gir-generate/gendata/gendata.go#L348

[Pid](ttps://docs.gtk.org/glib/alias.Pid.html) is an int on Linux and a process handle on Windows h

gtk-rs supports this: https://github.com/gi-rust/glib-sys/blob/cd5bf488b32b01cff76da88100ab9c7d2478fe9d/lib.rs#L86-L90

We could probably do something similar with go tags if we extend the generator. Thoughts? I'll probably try once I find the time, but perhaps you have some pointers

**Comment by diamondburned** [comment]
The easiest way to do this is to add `GPID` in as a built-in for `core/glib`. You can then add special code for this in `types`, `typeconv` and the `callable` generators. It's kind of a pain to do it, but it's the easiest way.

**Comment by diamondburned** [comment]
It might be best to declare the built-in as `type PID C.GPid` rather than using build tags.

**Comment by diamondburned** [comment]
Out of curiosity, have you tried combining `vte.Pty` with `os/exec.Command`? It looks like you could allocate a new `Pty` and use its `fd` as the value for `cmd.Stdout`?

Also, `Pty` should be strcased to be `PTY`.

**Comment by diamondburned** [comment]
Potentially this...

<img src="https://github.com/diamondburned/gotk4/assets/8463786/5a4e93cf-b877-4a74-bf02-b1aeefd15e92" alt="screenshot of terminal running bash mostly fine" width="600">

<details>
<summary>Code</summary>

```go
package main

import (
	"context"
	"os/exec"

	"github.com/creack/pty"
	"github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
	"github.com/jgillich/gotk4-vte/pkg/vte/v3"
)

func main() {
	app := gtk.NewApplication("so.libdb.gotk4-vte-test", gio.ApplicationFlagsNone)
	app.ConnectActivate(func() { activate(app) })
	app.Run(nil)
}

func activate(app *gtk.Application) {
	terminal := vte.NewTerminal()
	terminal.SetSize(80, 24)

	go func() {
		tty, err := pty.Start(exec.Command("bash"))
		if err != nil {
			panic(err)
		}

		pty, err := vte.NewPtyForeignSync(context.Background(), int(tty.Fd()))
		if err != nil {
			panic(err)
		}

		glib.IdleAdd(func() {
			terminal.SetPty(pty)
		})
	}()

	win := gtk.NewApplicationWindow(app)
	win.SetTitle("VTE Example")
	win.SetChild(terminal)
	win.Show()
}
```

</details>

**Comment by diamondburned** [comment]
strcases:

- `Pty` -> `PTY`
- `Tty` -> `TTY`
- `Icu` -> `ICU`
- `Cjk` -> `CJK`
- `Sixel` -> `SIXEL`

**Comment by diamondburned** [comment]
How's this!

<img src="https://github.com/diamondburned/gotk4/assets/8463786/27ffc530-7c48-461f-9fe8-0edd3fcfde5b" alt="vte example running neofetch in /bin/sh" width="600">

**Comment by diamondburned** [comment]
Windows compatibility will need to be tested... Note that `(*os.File).Fd()` on Windows returns a `uintptr`! Our `NewPtyForeignSync` is not portable because it still takes in an `int` there...

It might be a good idea to manually create a `vte_windows.go` file with a `type Fd = uintptr`, then generate `NewPtyForeignSync` to use `Fd` instead of `int`.

**Comment by jgillich** [comment]
Haha nice! Looks like I could've saved myself a lot of pain. creack/pty doesn't support Windows at all, but VTE's pty should work too...

#129 does at least compile now, but it's likely going to explode at runtime :smile:

**Comment by diamondburned** [comment]
> but VTE's pty should work too...

You might still want to get its functions working then... I can pick up the `glib.PID` PR in a few days likely. It seems to be a fairly important type.

Does glib have an `Fd` type already as well? We could add that in also.

**Comment by jgillich** [comment]
`terminal.PtyNewSync` already works, it's only the spawn function that's missing. At first I couldn't figure out how to hook it up, but after some Unix 101 I realized I needed a tty from the pty. Copied a few lines from creack/pty for now as I couldn't find it in VTE. https://github.com/getseabird/seabird/blob/535cce58b5d1919c5bc04b04d3e2cb54c9c52b8c/ui/terminal_page_unix.go#L43

But it appears that VTE doesn't support Windows at all. Bummer for my cross-platform app

**Comment by diamondburned** [comment]
> But it appears that VTE doesn't support Windows at all.

Oh, I actually didn't know that at all...

**Comment by pekim** [comment]
> But it appears that VTE doesn't support Windows at all.

Yes, there's a 5 year old issue, https://gitlab.gnome.org/GNOME/vte/-/issues/86. And it doesn't look likely that it'll be addressed any time soon.
