### ISSUE TITLE
Add a definition for GTK_INVALID_LIST_POSITION

### ISSUE THREAD

**Issue by nsw42** [diamondburned/gotk4#132]
gotk4 v0.2.2

The docs for [Gtk.DropDown.set_selected](https://docs.gtk.org/gtk4/method.DropDown.set_selected.html) says to pass in `GTK_INVALID_LIST_POSITION` to deselect any previous selection. This constant doesn't appear to be included in the generated bindings. 

If I manually define a const in my application with the value `glib.MAXUINT32` (which is, in effect, how [glib defines the constant](https://docs.gtk.org/gtk4/const.INVALID_LIST_POSITION.html)) it works as expected, so this should be as simple as adding an appropriately named constant.  (Based on other glib constants, I assume this would be `gtk.INVALID_LIST_POSITION`, to mirror e.g. `gtk.LEVEL_BAR_OFFSET_FULL`)

**Comment by diamondburned** [comment]
Added this in 748122820. I chose `InvalidListPosition` instead since it's more idiomatic.

**Comment by nsw42** [comment]
Perfect. Thanks.
(And, agreed about idiomatic. That's what I looked for first, before finding the LEVEL_BAR... constants)
