### ISSUE TITLE
PHP Warning: Undefined array key "menudirection" in log

### ISSUE THREAD

**Issue by Hobokens** [diamondburned/gotk4#149]
TYPO3 12.4.17
t3sbootstrap 5.3.12

I get lots of PHP Warnings in the log:
`Undefined array key "menudirection" in /www/htdocs/xxxxxx/my-domain.de/typo3conf/ext/t3sbootstrap/Classes/ContentElements/Menu.php line 23`

**Comment by diamondburned** [comment]
There is not a single line of PHP in this repository.

**Comment by Hobokens** [comment]
Sorry, wrong repository.
