### ISSUE TITLE
Undefined reference to `callbackDelete`

### ISSUE THREAD

**Issue by sigurd4** [diamondburned/gotk4#156]
# Error

Trying to update my packages, the package `walker` fails to build, which uses this package as a dependency. I get the following build error:

```
/usr/bin/ld: $WORK/b260/_x007.o: in function `gotk4_gbox_object_finalize':
/home/sigurd/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/gioutil/listmodel.c:24:(.text+0x7d1): undefined reference to `callbackDelete'
```

I've tried deleting my `~/go` folder to do a clean reinstall of all go dependencies but that didn't help.

# Environment

OS: Arch Linux x86_64
Host: HP EliteBook 8560w (XX058AV) A0001C02
Kernel: 6.12.4-arch1-1
DE: Hyprland
package version: gotk4@v0.3.1

**Comment by diamondburned** [comment]
Could you try latest commit 20a52bdb1eb4da00fe974d7b6c4e918e72d89c74?

**Comment by sigurd4** [comment]
Gonna have to wait for the package maintainers of `walker` to be able to test it. For now i'll just use their precompiled package.

**Comment by sigurd4** [comment]
I've never worked with go so i don't have a development environment set up to test the latest commit. Is there an easy way to just check if it builds on my machine (the library itself)?

**Comment by sigurd4** [comment]
Cloned the repo and ran `go build` and got no errors, so i think it works?
