### ISSUE TITLE
Get rid of gdesktopappinfo.go for Mac

### ISSUE THREAD

**Issue by vladimirschuka** [diamondburned/gotk4#28]
In Macs there is no such file `gio/gdesktopappinfo.h`  I read that file specific for linux and samples does not work with gtk4. I just deleted cgo includes and go file as a result could run simple example and drawingarea on my Apple M1.

**Comment by diamondburned** [comment]
Commit ce153061 should have this issue fixed.

**Comment by vladimirschuka** [comment]
Still there is problem, in go files there are rows `// #include <gio/gdesktopappinfo.h>`
When I delete all of them from the go files everything is ok. 
I use `go mod vendor ` to change go files.

Initial error:
`vendor/github.com/diamondburned/gotk4/pkg/gio/v2/gaction.go:17:11: fatal error: 'gio/gdesktopappinfo.h' file not found
 #include <gio/gdesktopappinfo.h>`

**Comment by diamondburned** [comment]
Seems like that include is hard-coded into the GIR file directly:

```xml
<repository version="1.2"
            xmlns="http://www.gtk.org/introspection/core/1.0"
            xmlns:c="http://www.gtk.org/introspection/c/1.0"
            xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <include name="GObject" version="2.0"/>
  <package name="gio-2.0"/>
  <package name="gio-unix-2.0"/>
  <c:include name="gio/gdesktopappinfo.h"/> <!-- here -->
  <c:include name="gio/gfiledescriptorbased.h"/>
  <c:include name="gio/gio.h"/>
  <c:include name="gio/gunixconnection.h"/>
  <c:include name="gio/gunixcredentialsmessage.h"/>
  <c:include name="gio/gunixfdlist.h"/>
  <c:include name="gio/gunixfdmessage.h"/>
  <c:include name="gio/gunixinputstream.h"/>
  <c:include name="gio/gunixmounts.h"/>
  <c:include name="gio/gunixoutputstream.h"/>
  <c:include name="gio/gunixsocketaddress.h"/>
```

**Comment by diamondburned** [comment]
Commit f1f3c33d no longer imports `gio/gdesktopappinfo.h`.
