### ISSUE TITLE
How to use window.SetTtitlebar

### ISSUE THREAD

**Issue by nekohasekai** [diamondburned/gotk4#30]
Sorry, I'm new to go and can't find out how to complete the typecast.

![image](https://user-images.githubusercontent.com/56506714/130312702-c5a36b9f-4a97-41ca-be04-197605d95675.png)

**Comment by diamondburned** [comment]
The latest commit should have no issue with casting `*gtk.HeaderBar` to
`gtk.Widgetter`.

Your gotk4 might be too old.

**Comment by nekohasekai** [comment]
I'm using[836111bce8a78e97f914e3f46a2da7e70d3c9bdb]([https://github.com/diamondburned/gotk4/commit/836111bce8a78e97f914e3f46a2da7e70d3c9bdb)

![Image](https://user-images.githubusercontent.com/56506714/130341616-1ed4e0ea-035b-4f96-9f8e-73a8ce423a54.png)

**Comment by diamondburned** [comment]
Does casting into `*gtk.HeaderBar` then manually passing in the `.Widget`
selector work?

**Comment by nekohasekai** [comment]
After copying wrapWidget, it succeeded

![](https://user-images.githubusercontent.com/56506714/130348822-1785feec-3d6f-4b69-bb9e-e0b77f57b681.png)

**Comment by nekohasekai** [comment]
After wrap functions [exported](https://github.com/SagerNet/gotk4/commit/02f306723b50c9f44ab99ae8c5feb55c6eac9156) :thinking: 

![](https://user-images.githubusercontent.com/56506714/130350167-32255f9a-9c83-4c7c-9734-fb1db8aa9989.png)

**Comment by nekohasekai** [comment]
Seems there is a problem with Cast?

![](https://user-images.githubusercontent.com/56506714/130351262-b6e2ab9d-7ba7-4dd2-96b6-b642fb296bed.png)
![](https://user-images.githubusercontent.com/56506714/130351358-6f1d1f9c-4e47-40dc-8f7d-9cc9e0745c66.png)

**Comment by diamondburned** [comment]
Does casting into `*gtk.HeaderBar` work?

**Comment by nekohasekai** [comment]
Seems no problem with gtk/v4
