### ISSUE TITLE
cairo write png image to memory 

### ISSUE THREAD

**Issue by smaznet** [diamondburned/gotk4#40]
## how to use this method?
`cairo_surface_write_to_png_stream`

im using this code to save image to file
`surface.WriteToPNG("./file.png") `
but i dont want do that
i want to pass byte data directly to http response

`	res.Write(data)`

**Comment by diamondburned** [comment]
The `cairo` package is manually written, so if it's not there, then you could just PR in a hand-written implementation directly in the package.

**Comment by smaznet** [comment]
> The `cairo` package is manually written, so if it's not there, then you could just PR in a hand-written implementation directly in the package.

Sorry im new to golang and i don't know how i can handle callbacks

**Comment by diamondburned** [comment]
No worries. I'll get to this tomorrow if I can.

**Comment by diamondburned** [comment]
Commit d2e12b4d adds `cairo.Surface.WriteToPNGWriter`, which is a wrapper over
this function. No callback is needed from the user; you can just put a
`http.ResponseWriter` directly in it.

**Comment by smaznet** [comment]
Thanks ❤️
