### ISSUE TITLE
The examples are great but can we also have a getting started guide?

### ISSUE THREAD

**Issue by alshdavid** [diamondburned/gotk4#53]
This is my first intro into native desktop applications on Linux and after seeing how cool Gnome 4x is; I am keen to get started and contribute to the ecosystem. 

Sadly, I don't have the benefit of understanding the context and history so I don't know what dependencies I need to get set up. Naturally I set up the starter project and I googled error messages until I stopped getting error messages. Currently the `go run` and `go build` commands hang silently.

A basic getting started guide would be awesome.
To try to get everything going I ran:

```bash
# Install OS dependencies
sudo apt install pkg-config libgtk-4-dev -y

# Install Go
wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf ./go1.17.5.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version

# Create project
mkdir testapp
cd testapp
go mod init testapp

# Install project dependencies
go get -u github.com/diamondburned/gotk4/pkg/gtk/v4

# Obtain simple hello world application
wget https://raw.githubusercontent.com/diamondburned/gotk4-examples/master/gtk4/simple/main.go

# Run application
go build main.go
./main.go
```

However, when I attempt to get the hello world application running using the Hello World example `go run` hangs.

![image](https://user-images.githubusercontent.com/12656294/147399654-c86960cf-27e4-4385-b56f-0e3e6a5de715.png)

**Comment by diamondburned** [comment]
Right. A lot of people seem to think that `go run` "hangs", when in actuality,
`go run` is just really, really slow when it comes to Cgo.

I would prefer these kinds of instructions to go to the examples repository
instead. I'll see what can be added beyond clarifying that.

As for fetching the latest version of Go, are you perhaps new to the language?
There are lots of resources out there, such as
[doc/code](https://golang.org/doc/code), that can get you started on writing Go
programs, so I won't be clarifying that in the resources.

**Comment by alshdavid** [comment]
> `go run` is just really, really slow when it comes to Cgo.

I see. Left it for a while and yep, a window appeared. Compiling it again is faster than the first time.

> I'll see what can be added beyond clarifying that.

I'm happy to raise a PR assuming my steps are correct.

> As for fetching the latest version of Go

I am following the install instructions from the [Go website](https://go.dev/doc/install). Otherwise I am pretty confident with actually writing Go code.

Thanks for this library! 

![image](https://user-images.githubusercontent.com/12656294/147400335-7e96b90a-a709-4385-b21e-4a4646d8f94e.png)

**Comment by diamondburned** [comment]
I've added some information into the README of
[gotk4-examples](https://github.com/diamondburned/gotk4-examples). Let me know
if there's anything missing and/or needs to be added.

**Comment by alshdavid** [comment]
Hope you don't mind me asking dumb questions and raising pull requests on the example repo while I get up to speed on the project 😆
