### ISSUE TITLE
GtkSourceView 5

### ISSUE THREAD

**Issue by pekim** [diamondburned/gotk4#57]
Would you consider adding bindings for Gtk SourceView 5 please?
https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by diamondburned** [comment]
GtkSourceView bindings will have to be in another repository. It should be fairly easy to add it, though. Closing this issue since it shouldn't be in this repository, but I can paste a link once I've generated it.

**Comment by diamondburned** [comment]
https://github.com/diamondburned/gotk4-sourceview

**Comment by pekim** [comment]
That's great. I really appreciate how quickly you've responded. Thank you very much.
