### ISSUE TITLE
No proper type conversion generated for signals

### ISSUE THREAD

**Issue by pekim** [diamondburned/gotk4#58]
```go
app := gtk.NewApplication("uk.co.pekim.Mige", gio.ApplicationHandlesOpen)
app.ConnectOpen(func(files []gio.Filer, hint string) {
	fmt.Println(len(files))
})
```

```
panic: reflect.Value.Convert: value of type unsafe.Pointer cannot be converted to type []gio.Filer [recovered]
	panic: closure error: unexpected panic caught: reflect.Value.Convert: value of type unsafe.Pointer cannot be converted to type []gio.Filer
```

**Comment by diamondburned** [comment]
Right, the `ConnectX` method generation is not perfect. I'll have to figure out proper type conversion generation for the signals. I'll keep this issue open until that's implemented.

**Comment by pekim** [comment]
https://github.com/diamondburned/gotk4/issues/60#issuecomment-1031027207
> should be fixed along with https://github.com/diamondburned/gotk4/issues/58

No change I'm afraid. The same conversion failure occurs.

**Comment by diamondburned** [comment]
Oh yeah, #58 is unimplemented. I'm planning on rebasing some work from the subclassing branch over once it works, but the large changes will take me a while and I currently can't work on large, time-consuming changes.

**Comment by diamondburned** [comment]
This issue is a bit more tedious than I anticipated. How exactly should I index a `C.gpointer` of underlying type `*C.GFile`? Go complains that `unsafe.Slice((*C.GFile)(nil), 0)` is not valid because it cannot get the size of a `GFile` instance, which is kind of weird.

Should I be doing `unsafe.Slice((*C.GObject)(nil), 0)`?

**Comment by diamondburned** [comment]
It turns out (to nobody's surprise) that the parameter's type is actually `GFile**` despite the GIR data saying otherwise.

**Comment by diamondburned** [comment]
@pekim can you try commit c88e9b851? It should now be possible to do

```go
app.ConnectOpen(func(files []gio.Filer, hint string) {
	fmt.Println(len(files))
})
```

**Comment by pekim** [comment]
Yes, that works. Thank you very much.
