### ISSUE TITLE
TreeView row-activated signal handler - conversion failure

### ISSUE THREAD

**Issue by pekim** [diamondburned/gotk4#60]
```go
view := gtk.NewTreeView()
view.ConnectRowActivated(func(path *gtk.TreePath, column gtk.TreeViewColumn) {
	fmt.Println(path.String())
})
```

When the `row-activated` signal is triggered, the column argument is not converted to the correct type, resulting in a panic.

```
panic: reflect.Value.Convert: value of type *gtk.TreeViewColumn cannot be converted to type gtk.TreeViewColumn [recovered]
	panic: closure error: unexpected panic caught: reflect.Value.Convert: value of type *gtk.TreeViewColumn cannot be converted to type gtk.TreeViewColumn
```

**Comment by pekim** [comment]
I can workaround this for now as I don't currently need to know the column.

```go
view := gtk.NewTreeView()
view.Connect("row-activated", func(path *gtk.TreePath) {
	fmt.Println("activated", path.String())
})
```

**Comment by diamondburned** [comment]
This has to do with the code generator being weird with the edge cases. The correct function signature is

```go
view.Connect("row-activated", func(path *gtk.TreePath, column *gtk.TreeViewColumn) {
	fmt.Println(path.String())
})
```

**Comment by diamondburned** [comment]
I think this should be fixed along with https://github.com/diamondburned/gotk4/issues/58, since the signature generation should be a lot more correct if it's generated with the type converter.

**Comment by pekim** [comment]
This now works, which is great.
```go
view.Connect("row-activated", func(path *gtk.TreePath, column *gtk.TreeViewColumn) {
	fmt.Println(path.String())
})
```

However it's worth noting that the original conversion issue with `ConnectRowActivated` still remains. That's probably not too surprising as the function's signature has not changed.

**Comment by diamondburned** [comment]
@pekim can you recheck this? The generated function signature for this signal should now be

```go
func (treeView *TreeView) ConnectRowActivated(f func(path *TreePath, column *TreeViewColumn)) externglib.SignalHandle
```

which is the correct signature.

**Comment by pekim** [comment]
Yes, it's good now. Thank you.
