### ISSUE TITLE
Stuck on "Login to gtkcord3"

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gotk4#65]
After installing, I'm stuck here
![image](https://user-images.githubusercontent.com/44733677/155052895-d0d471d8-6b5e-45ad-8a53-6d4a13e7a38e.png)

**Comment by diamondburned** [comment]
This isn't related to gotk4.

**Comment by ThatOneCalculator** [comment]
wait lmao i did this under the wrong repo oops
