### ISSUE TITLE
Stuck at "go get github.com/diamondburned/gotk4/pkg/gtk/v4"

### ISSUE THREAD

**Issue by progopher1** [diamondburned/gotk4#66]
The command is stuck with no output at all. I am using Arch Linux, I have installed all of the dependencies for GTK4 (`gtk4`, `glib`, etc.)

**Comment by diamondburned** [comment]
Not stuck. It's just slow.

See https://github.com/diamondburned/gotk4/issues/53#issuecomment-1001109930.

Also see https://github.com/golang/go/issues/9887#issuecomment-913056050.
