### ISSUE TITLE
support building without gobject-introspection & atk

### ISSUE THREAD

**Issue by sewnie** [diamondburned/gotk4#91]
if gtk+4 can have `-Dintrospection=disabled`, and can be built without atk (without touching source code), why cant gotk4?

**Comment by diamondburned** [comment]
Some functions generated by the code generator need gobject-introspection. In the future, the code generator will also generate code that uses gobject-introspection, so there's no getting around that.

There's also no good reason to not include either gobject-introspection or atk.

**Comment by sewnie** [comment]
I didn't ask to remove it, I'm asking to keep it optional. much like gtk4 build can.

**Comment by diamondburned** [comment]
Again, there are plans to generate code that depends on gobject-introspection. That's not becoming optional anytime soon.
